package org.ec.mh.dao.mapper;


import org.ec.mh.entity.AppModule;

public interface AppModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_module
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_module
     *
     * @mbggenerated
     */
    int insert(AppModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_module
     *
     * @mbggenerated
     */
    int insertSelective(AppModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_module
     *
     * @mbggenerated
     */
    AppModule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppModule record);
}