package org.ec.mh.dao.mapper;


import org.ec.mh.entity.PermissionAssign;

public interface PermissionAssignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_assign
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_assign
     *
     * @mbggenerated
     */
    int insert(PermissionAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_assign
     *
     * @mbggenerated
     */
    int insertSelective(PermissionAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_assign
     *
     * @mbggenerated
     */
    PermissionAssign selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_assign
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PermissionAssign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_assign
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PermissionAssign record);
}