package org.ec.mh.dao.mapper;


import org.ec.mh.entity.RolePermissionPoint;

public interface RolePermissionPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_point
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_point
     *
     * @mbggenerated
     */
    int insert(RolePermissionPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_point
     *
     * @mbggenerated
     */
    int insertSelective(RolePermissionPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_point
     *
     * @mbggenerated
     */
    RolePermissionPoint selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RolePermissionPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission_point
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RolePermissionPoint record);
}