package org.ec.mh.entity;

public class AppModuleAssignment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_module_assignment.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_module_assignment.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_module_assignment.app_module_id
     *
     * @mbggenerated
     */
    private String appModuleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_module_assignment.id
     *
     * @return the value of app_module_assignment.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_module_assignment.id
     *
     * @param id the value for app_module_assignment.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_module_assignment.role_id
     *
     * @return the value of app_module_assignment.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_module_assignment.role_id
     *
     * @param roleId the value for app_module_assignment.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_module_assignment.app_module_id
     *
     * @return the value of app_module_assignment.app_module_id
     *
     * @mbggenerated
     */
    public String getAppModuleId() {
        return appModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_module_assignment.app_module_id
     *
     * @param appModuleId the value for app_module_assignment.app_module_id
     *
     * @mbggenerated
     */
    public void setAppModuleId(String appModuleId) {
        this.appModuleId = appModuleId == null ? null : appModuleId.trim();
    }
}