package org.ec.mh.entity;

public class Module {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.module_code
     *
     * @mbggenerated
     */
    private String moduleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.owner_type
     *
     * @mbggenerated
     */
    private String ownerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.has_child
     *
     * @mbggenerated
     */
    private Byte hasChild;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.level0
     *
     * @mbggenerated
     */
    private Integer level0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.module_name
     *
     * @mbggenerated
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.is_menu
     *
     * @mbggenerated
     */
    private Byte isMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.is_menu_page
     *
     * @mbggenerated
     */
    private Byte isMenuPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.parent_code
     *
     * @mbggenerated
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.show_order
     *
     * @mbggenerated
     */
    private Integer showOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.child_show_type
     *
     * @mbggenerated
     */
    private String childShowType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.is_read
     *
     * @mbggenerated
     */
    private Byte isRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.id
     *
     * @return the value of module.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.id
     *
     * @param id the value for module.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.module_code
     *
     * @return the value of module.module_code
     *
     * @mbggenerated
     */
    public String getModuleCode() {
        return moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.module_code
     *
     * @param moduleCode the value for module.module_code
     *
     * @mbggenerated
     */
    public void setModuleCode(String moduleCode) {
        this.moduleCode = moduleCode == null ? null : moduleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.owner_type
     *
     * @return the value of module.owner_type
     *
     * @mbggenerated
     */
    public String getOwnerType() {
        return ownerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.owner_type
     *
     * @param ownerType the value for module.owner_type
     *
     * @mbggenerated
     */
    public void setOwnerType(String ownerType) {
        this.ownerType = ownerType == null ? null : ownerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.has_child
     *
     * @return the value of module.has_child
     *
     * @mbggenerated
     */
    public Byte getHasChild() {
        return hasChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.has_child
     *
     * @param hasChild the value for module.has_child
     *
     * @mbggenerated
     */
    public void setHasChild(Byte hasChild) {
        this.hasChild = hasChild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.level0
     *
     * @return the value of module.level0
     *
     * @mbggenerated
     */
    public Integer getLevel0() {
        return level0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.level0
     *
     * @param level0 the value for module.level0
     *
     * @mbggenerated
     */
    public void setLevel0(Integer level0) {
        this.level0 = level0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.module_name
     *
     * @return the value of module.module_name
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.module_name
     *
     * @param moduleName the value for module.module_name
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.is_menu
     *
     * @return the value of module.is_menu
     *
     * @mbggenerated
     */
    public Byte getIsMenu() {
        return isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.is_menu
     *
     * @param isMenu the value for module.is_menu
     *
     * @mbggenerated
     */
    public void setIsMenu(Byte isMenu) {
        this.isMenu = isMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.is_menu_page
     *
     * @return the value of module.is_menu_page
     *
     * @mbggenerated
     */
    public Byte getIsMenuPage() {
        return isMenuPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.is_menu_page
     *
     * @param isMenuPage the value for module.is_menu_page
     *
     * @mbggenerated
     */
    public void setIsMenuPage(Byte isMenuPage) {
        this.isMenuPage = isMenuPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.parent_code
     *
     * @return the value of module.parent_code
     *
     * @mbggenerated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.parent_code
     *
     * @param parentCode the value for module.parent_code
     *
     * @mbggenerated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.show_order
     *
     * @return the value of module.show_order
     *
     * @mbggenerated
     */
    public Integer getShowOrder() {
        return showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.show_order
     *
     * @param showOrder the value for module.show_order
     *
     * @mbggenerated
     */
    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.url
     *
     * @return the value of module.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.url
     *
     * @param url the value for module.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.child_show_type
     *
     * @return the value of module.child_show_type
     *
     * @mbggenerated
     */
    public String getChildShowType() {
        return childShowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.child_show_type
     *
     * @param childShowType the value for module.child_show_type
     *
     * @mbggenerated
     */
    public void setChildShowType(String childShowType) {
        this.childShowType = childShowType == null ? null : childShowType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.is_read
     *
     * @return the value of module.is_read
     *
     * @mbggenerated
     */
    public Byte getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.is_read
     *
     * @param isRead the value for module.is_read
     *
     * @mbggenerated
     */
    public void setIsRead(Byte isRead) {
        this.isRead = isRead;
    }
}