package org.ec.mh.entity;

public class PermissionPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_point.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_point.module_code
     *
     * @mbggenerated
     */
    private String moduleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_point.operation_code
     *
     * @mbggenerated
     */
    private String operationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission_point.operation_name
     *
     * @mbggenerated
     */
    private String operationName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_point.id
     *
     * @return the value of permission_point.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_point.id
     *
     * @param id the value for permission_point.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_point.module_code
     *
     * @return the value of permission_point.module_code
     *
     * @mbggenerated
     */
    public String getModuleCode() {
        return moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_point.module_code
     *
     * @param moduleCode the value for permission_point.module_code
     *
     * @mbggenerated
     */
    public void setModuleCode(String moduleCode) {
        this.moduleCode = moduleCode == null ? null : moduleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_point.operation_code
     *
     * @return the value of permission_point.operation_code
     *
     * @mbggenerated
     */
    public String getOperationCode() {
        return operationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_point.operation_code
     *
     * @param operationCode the value for permission_point.operation_code
     *
     * @mbggenerated
     */
    public void setOperationCode(String operationCode) {
        this.operationCode = operationCode == null ? null : operationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission_point.operation_name
     *
     * @return the value of permission_point.operation_name
     *
     * @mbggenerated
     */
    public String getOperationName() {
        return operationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission_point.operation_name
     *
     * @param operationName the value for permission_point.operation_name
     *
     * @mbggenerated
     */
    public void setOperationName(String operationName) {
        this.operationName = operationName == null ? null : operationName.trim();
    }
}