package org.ec.mh.entity;

public class RolePermissionPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_point.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_point.permission_assign_id
     *
     * @mbggenerated
     */
    private String permissionAssignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission_point.permission_point_id
     *
     * @mbggenerated
     */
    private String permissionPointId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_point.id
     *
     * @return the value of role_permission_point.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_point.id
     *
     * @param id the value for role_permission_point.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_point.permission_assign_id
     *
     * @return the value of role_permission_point.permission_assign_id
     *
     * @mbggenerated
     */
    public String getPermissionAssignId() {
        return permissionAssignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_point.permission_assign_id
     *
     * @param permissionAssignId the value for role_permission_point.permission_assign_id
     *
     * @mbggenerated
     */
    public void setPermissionAssignId(String permissionAssignId) {
        this.permissionAssignId = permissionAssignId == null ? null : permissionAssignId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission_point.permission_point_id
     *
     * @return the value of role_permission_point.permission_point_id
     *
     * @mbggenerated
     */
    public String getPermissionPointId() {
        return permissionPointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission_point.permission_point_id
     *
     * @param permissionPointId the value for role_permission_point.permission_point_id
     *
     * @mbggenerated
     */
    public void setPermissionPointId(String permissionPointId) {
        this.permissionPointId = permissionPointId == null ? null : permissionPointId.trim();
    }
}